name: Release (GitHub/PyPI)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Trigger on all tags initially, but tag and release privilege are verified in _build-wheel-release-upload.yml

jobs:
  release:
    permissions:
      contents: write
    uses: Billingegroup/release-scripts/.github/workflows/_build-wheel-release-upload.yml@override-admin-tag
    with:
      project: diffpy.labpdfproc
      github_admin_username: bobleesj

    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
