name: Check for News

on:
  pull_request_target:
    branches:
      - main

jobs:
  check-news-item:
    uses: bobleesj/release-scripts/.github/workflows/_check-news-item.yml@news-file-warning
    with:
      project: diffpy.utils
