name: Deploy Documentation on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    uses: bobleesj/release-scripts/.github/workflows/_publish-docs-on-release.yml@v0
    with:
      project: diffpy.labpdfproc
      c_extension: false
