name: Release on GitHub on tag push

on:
  workflow_dispatch:
  push:
    tags:
      - "*" # Trigger on all tags initially, but tag and release privilege are verified in _build-wheel-release-upload.yml

jobs:
  release:
    uses: bobleesj/release-scripts/.github/workflows/_build-wheel-release-upload.yml@gh-release-workflow
    with:
      maintainer_GITHUB_username: bobleesj
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
