name: Tests on PR

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: bobleesj/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: bobleesj.release
      c_extension: false
      headless: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}